HELPERS/Models/Formulario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace HTMLhelpers.Models
{
    public class Formulario
    {

        public int ID { get; set; }

        [Required(ErrorMessage = "Campo Requerido")]
        public String cedula { get; set; }

        [Required(ErrorMessage = "Campo Requerido")]
        public String nombre { get; set; }

        [Required(ErrorMessage = "Campo Requerido")]
        public String apellido { get; set; }

        [Range(15,100,ErrorMessage ="Debes ser mayor de 15 años")]
        [Required(ErrorMessage = "Campo Requerido")]
        public int edad { get; set; }

        [MinLength(10)]
        public String telefono { get; set; }

        [EmailAddress(ErrorMessage ="Correo no encontrado")]
        [RegularExpression("^[_A-Za-z'`+-.]+([_A-Za-z0-9'+-.]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9]+)*(\\.([A-Za-z]*){3,})$", ErrorMessage = "Formato incorrecto")]
        [Required(ErrorMessage ="El correo es requerido")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Formato Incorrecto")]
        public String Correo { get; set; }

        public String genero { get; set; }

        public String estado { get; set; }

        //public string[] hobbies { get; set; }

        public bool hobby1 { get; set; }
        public bool hobby2 { get; set; }
        public bool hobby3 { get; set; }
        public bool hobby4 { get; set; }


        public generos GenerosPersonas { get; set; }

    }

    public enum generos
    {
        Masculino,
        Femenino,
        Otro
    }
}

HELPERS/Models/FormularioContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace HTMLhelpers.Models
{
    public class FormularioContext:DbContext
    {   
        public FormularioContext()
            : base("FormularioDatBase")
        { 
        }

        public DbSet<Formulario> formulario { get; set; }
    }
}

HELPERS/Controllers/FormulariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HTMLhelpers.Models;

namespace HELPERS.Controllers
{
    public class FormulariosController : Controller
    {
        private FormularioContext db = new FormularioContext();

        // GET: Formularios
        public ActionResult Index()
        {
            return View(db.formulario.ToList());
        }

        // GET: Formularios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.formulario.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // GET: Formularios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Formularios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,cedula,nombre,apellido,edad,telefono,Correo,genero,estado,hobbies")] Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                db.formulario.Add(formulario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(formulario);
        }

        // GET: Formularios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.formulario.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // POST: Formularios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,cedula,nombre,apellido,edad,telefono,Correo,genero,estado,hobbies")] Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formulario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(formulario);
        }

        // GET: Formularios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.formulario.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // POST: Formularios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Formulario formulario = db.formulario.Find(id);
            db.formulario.Remove(formulario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HELPERS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HELPERS.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

HELPERS/Views/Formularios/Create.cshtml
@model HTMLhelpers.Models.Formulario
    @using HTMLhelpers.Models
@{
    ViewBag.Title = "Nuevo";
}

<h2>Opción de Crear</h2>

<style>

</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Formulario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cedula,"Cedula:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="cedula">
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre,"Nombre:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nombre">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellido,"Apellido:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="apellido">
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.edad,"Edad:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="edad">
                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono,"Telefono:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="telefono">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo,"Correo:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="correo">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genero,"Genero:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="dropdown">
               @Html.DropDownListFor(model=>model.genero, 
               new SelectList(Enum.GetValues(typeof(generos))),
               "Seleccione...")
                @Html.ValidationMessageFor(model => model.genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado,"Estado:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="radiobutton-estado">
               | @Html.RadioButtonFor(model=>model.estado, "Soltero/a") Soltero/a  |
                @Html.RadioButtonFor(model => model.estado, "Casado/a") Casado/a  |
                @Html.RadioButtonFor(model => model.estado, "Viudo/a") Viudo/a  |
                @Html.RadioButtonFor(model => model.estado, "Union libre") Union Libre  |
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hobby1,"Hobbies:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="checkbox-hobbies">
                @*@Html.CheckBoxFor(model => model.hobby1, checked)*@
               @*| @Html.CheckBox("hobbies[]", false, new { @value = "Programar" }) Programar  |
                @Html.CheckBox("hobbies[]", false, new { @value = "Escuchar Musica" }) Escuchar Musica  |
                @Html.CheckBox("hobbies[]", false, new { @value = "Videojuegos" }) Videojuegos  |
                @Html.CheckBox("hobbies[]", false, new { @value = "Escribir" }) Escribir  |*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div class="nav nav-pills">
        @Html.ActionLink("VOLVER ATRAS", "Index")
    </div>

HELPERS/Views/Formularios/Delete.cshtml
@model HTMLhelpers.Models.Formulario

@{
    ViewBag.Title = "Borrar";
}

<h2>Opción de Borrar</h2>

<h3>¿Estás seguro que desea eliminar?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hobbies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hobbies)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("VOLVER ATRAS", "Index")
        </div>
    }
</div>

HELPERS/Views/Formularios/Details.cshtml
@model HTMLhelpers.Models.Formulario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hobbies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hobbies)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HELPERS/Views/Formularios/Edit.cshtml
@model HTMLhelpers.Models.Formulario

@{
    ViewBag.Title = "Editar";
}

<h2>Opción de Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Formulario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.cedula, "Cedula:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, "Nombre:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellido, "Apellido:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.edad, "Edad:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, "Telefono:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, "Correo:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genero, "Genero:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, "Estado:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hobbies, "Hobbies:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hobbies, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hobbies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("VOLVER ATRAS", "Index")
</div>

HELPERS/Views/Formularios/Index.cshtml
@model IEnumerable<HTMLhelpers.Models.Formulario>
@{
    ViewBag.Title = "Inicio";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<head>
    <style>
        .cuerpo {
            background-image: url();
            background-size: cover;
        }

        .formulario {
            border-radius: 25px;
            margin-left: 20px;
            margin-right: 20px;
            position: center;
            background-color: #FFF4EC;
            border-radius: 10px;
        }
    </style>
</head>
<body class="cuerpo">
    <div class="formulario">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.cedula)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.edad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.telefono)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Correo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.genero)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.estado)
                </th>
                <th>
                    <p>hobbies</p>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.cedula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.edad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Correo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.genero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>  
                <td>
                    @Html.DisplayFor(modelItem => item.hobby1)
                    @*@if(Model.hobby1 is )*@
                </td>
                <td>
                    @Html.ActionLink("EDITAR", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("BORRAR", "Delete", new { id = item.ID })
                </td>
            </tr>
            }

        </table>
    </div>

    <div>
        @*@for (int item1 = 0; item1 < Model.hobbies.Length; item1++)
        {
            if (Model.hobbies[item1] != "false")
            {
                Model.hobbies[item1])
            }
         }*@
    </div>
</body>

HELPERS/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>

<head>

    <title>
        Pagina principal
    </title>

    <style>
        .estilo {
            background-image: url(https://images.pexels.com/photos/265047/pexels-photo-265047.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
            background-size: cover;
            /*background-attachment: fixed;*/
        }

        .encabezado{
            margin-right:300px;
            margin-top:300px;
            font-family:'Lucida Calligraphy';
            font-size:100px;
            color:black;
            text-align-last:center;
        }

       
    </style>

</head>


<body class="estilo" >
    <p class="encabezado" >Bienvenido al</p>
    <p class="encabezado" style="margin-top:0px;" >Formulario</p>
</body>

</html>

HELPERS/Views/Shared/_Layout.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Formulario</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Personas", "Index", "Formularios", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    @RenderBody()

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>